<article class="grid_12">
    <h1>Add news</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" required value=""/>
            </span>
            {if isset($errors["title"])}
            <span class="error">
                {echo join("<br/>", $errors["title"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Text*</label>
            <span class="field">
                <textarea name="body" rows="8" class="longinput"></textarea>
            </span>
            {if isset($errors["body"])}
            <span class="error">
                {echo join("<br/>", $errors["body"])}
            </span>
            {/if}
        </p>
<br/>
        <table class="dt-base">
            <thead>
            <th>Checkbox</th><th>Photo</th>
            <th>Checkbox</th><th>Photo</th>
            </thead>
            <tbody>
                {script $a=0;}
                {foreach $photo in $allphotos}
                {if $a%2==0}
                <tr>
                    <td><input type="checkbox" name="photos[]" value="{echo $photo->id}" /></td>
                    <td><img src="{echo $photo->pathSmall}" alt="" width="200"/></td>
                    {script $a++;}
                {/if}
                {else}
                    <td><input type="checkbox" name="photos[]" value="{echo $photo->id}" /></td>
                    <td><img src="{echo $photo->pathSmall}" alt="" width="200"/></td>
                </tr>
                {script $a++;}
                {/else}
                {/foreach}
            </tbody>
        </table>

        <p>
            <span class="field">
                <input type="submit" name="addNews" value="Add news" />
            </span>
        </p>
    </form>
    
    
</article>