<article class="grid_12">
    <h1>Delete News</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" class="mediuminput" disabled value="{echo $news->title}"/>
            </span>
        </p>
        <p>
            <label>Text</label>
            <span class="field">
                <input type="text" name="body" class="mediuminput" disabled value="{echo substr($news->body,0,300)}..."/>
            </span>
        </p>
        <p>
            <label>Created</label>
            <span class="field">
                <input type="text" name="created" class="mediuminput" disabled value="{echo $news->created}"/>
            </span>
        </p>
        <p>
            <span class="field">
                <input type="submit" name="deleteNews" value="Delete news" />
                <input type="submit" name="cancel" value="Cancel" />
            </span>
        </p>
    </form>
</article>