<article class="grid_12">
    <h1>Edit news</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" required value="{echo $news->title}"/>
            </span>
            {if isset($errors["title"])}
            <span class="error">
                {echo join("<br/>", $errors["title"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Text*</label>
            <span class="field">
                <textarea name="body" rows="8" class="longinput">{echo $news->body}</textarea>
            </span>
            {if isset($errors["body"])}
            <span class="error">
                {echo join("<br/>", $errors["body"])}
            </span>
            {/if}
        </p>
        
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $news->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["active"])}
            <span class="error">
                {echo join("<br/>", $errors["active"])}
            </span>
            {/if}
        </p>

        <br/>
        <p>
            <label></label>
            <span class="field">
                Selected photos
            </span>
        </p>
        
        <table class="dt-base">
            <thead>
            <th>Checkbox</th><th>Photo</th>
            <th>Checkbox</th><th>Photo</th>
            </thead>
            <tbody>
                {if !empty($selectedphotos)}
                {script $a=0}
                {foreach $photo in $selectedphotos}
                {if $a%2==0}
                <tr>
                    <td><input type="checkbox" name="photos[]" value="{echo $photo[id]}" checked /></td>
                    <td><img src="{echo $photo[pathSmall]}" alt="" width="200"/></td>
                    {script $a++}
                {/if}
                {else}
                    <td><input type="checkbox" name="photos[]" value="{echo $photo[id]}" checked /></td>
                    <td><img src="{echo $photo[pathSmall]}" alt="" width="200"/></td>
                </tr>
                {script $a++}
                {/else}
                {/foreach}
                {/if}
            </tbody>
        </table>
        
        <p>
            <label></label>
            <span class="field">
                All photos
            </span>
        </p>
        
        <table class="dt-base">
            <thead>
            <th>Checkbox</th><th>Photo</th>
            <th>Checkbox</th><th>Photo</th>
            </thead>
            <tbody>
                {if !empty($allphotos)}
                {script $a=0}
                {foreach $aphoto in $allphotos}
                {if $a%2==0}
                <tr>
                    <td><input type="checkbox" name="photos[]" value="{echo $aphoto->id}" /></td>
                    <td><img src="{echo $aphoto->pathSmall}" alt="" width="200"/></td>
                    {script $a++}
                {/if}
                {else}
                    <td><input type="checkbox" name="photos[]" value="{echo $aphoto->id}" /></td>
                    <td><img src="{echo $aphoto->pathSmall}" alt="" width="200"/></td>
                </tr>
                {script $a++}
                {/else}
                {/foreach}
                {/if}
            </tbody>
        </table>
        
        <p>
            <span class="field">
                <input type="submit" name="editNews" value="Save changes" />
            </span>
        </p>
    </form>
</article>