<article class="grid_12">
    <h1 class="left">News</h1>
    <a class="button-orange right" href="/admin/news/add/">+ Add News</a>
    <div class="clear"></div><br/><br/>

    {if !empty($news)}
    <table class="dt-base">
        <thead>
        <th>Title</th><th>Text</th><th>Active</th>
        <th>Created</th><th>Manage</th>
        </thead>
        <tbody>
            {foreach $_news in $news}
            <tr>
                <td>{echo $_news->title}</td>
                <td>{echo nl2br(substr($_news->body, 0, 400))}</td>
                <td>{echo $_news->active}</td>
                <td>{echo $_news->created}</td>
                <td>
                    <a class="button-edit" href="/admin/news/edit/{echo $_news->id}" >Edit</a>
                    <a class="button-delete" href="/admin/news/delete/{echo $_news->id}" >Delete</a>
                </td>
            </tr>
            {/foreach}
        </tbody>
    </table>
    {/if}
</article>