<article class="grid_12">
    <h1>Add gallery</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" class="longinput" required value="" />
            </span>
            {if isset($errors["title"])}
            <span class="error">
                {echo join("<br/>", $errors["title"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Description</label>
            <span class="field">
                <textarea cols="15" rows="5" name="description" class="longinput"></textarea>
            </span>
            {if isset($errors["description"])}
            <span class="error">
                {echo join("<br/>", $errors["description"])}
            </span>
            {/if}
        </p>
        
        <p>
            <span class="field">
                <input type="submit" name="addGallery" value="Add gallery" />
            </span>
        </p>
    </form>
</article>