<article class="grid_12">
    <h1>Photo upload</h1>

    {if isset($photoMessage)}
    <div class="gallery-upload-error">
        {echo $photoMessage}
    </div>
    {/if}
    <form class="stdform uploadPhotoForm" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>

        <p>
            <label>Photo</label>
            <span class="field">
                <input type="file" name="photo[]" /> <a href="#" class="multi-upload"><span>Multi-upload</span></a>
            </span> 
        </p>

        <p>
            <span class="field">
                <input type="submit" name="uploadPhoto" value="Upload photo" />
            </span>
        </p>
    </form>
</article>