<article class="grid_12">
    <h1>Delete user account</h1>
    
    <form method="post" action="#" class="stdform">
        <p>
            <label>Jméno</label>
            <span class="field">
                <input type="text" name="firstname" class="mediuminput" disabled value="{echo $user->firstname}"/>
            </span>
        </p>
        <p>
            <label>Příjmení</label>
            <span class="field">
                <input type="text" name="lastname" class="mediuminput" disabled value="{echo $user->lastname}">
            </span>
        </p>
        <p>
            <label>Email</label>
            <span class="field">
                <input type="email" name="email" class="mediuminput" disabled value="{echo $user->email}">
            </span>
        </p>
        <p>
            <span class="field">
                <input type="submit" name="deleteUser" value="Delete user account" />
                <input type="submit" name="cancel" value="Cancel" />
            </span>
        </p>
    </form>
</article>