<article class="adminLogin">
    <h1 class="nadpis">Přihlášení k administraci</h1>
    <form method="post" action="#" class="stdform">
        <p>
            {if isset($account_error)}
            <span class="error">
                {echo $account_error}
            </span>
            {/if}
        </p>
        <p>
        <table class="loginAdmin">
            <tr>
                <td>
                    Email
                </td>
                <td>
                    <input type="email" name="email" class="loginInput" required/>
                </td>
                <td> {if isset($email_error)}
                    <span class="error">
                        {echo $email_error}
                    </span>{/if}
                </td>
            </tr>
            <tr>
                <td>
                    Password
                </td>
                <td>
                    <input type="password" name="password" class="loginInput" required/>
                </td>
                <td>
                    {if isset($password_error)}
                    <span class="error">
                        {echo $password_error}
                    </span>
                    {/if}
                </td>
            </tr>
        </table>
        </p>
        <p>
            <div class="buttonWrapperAdmin">
                <input class="chatButton" type="submit" name="login" value="Přihlásit" />
            </div>
        </p>

    </form>
</article>