<article class="grid_12">
    <h1>Profil</h1>
    <form method="post" action="#" class="stdform" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>
        <p>
            <label>Jméno*</label>
            <span class="field">
                <input type="text" name="firstname" class="longinput" required value="{echo $user->firstname}"/>
            </span>
            {if isset($errors["firstname"])}
            <span class="error">
                {echo join("<br/>", $errors["firstname"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Příjmení*</label>
            <span class="field">
                <input type="text" name="lastname" class="longinput" required value="{echo $user->lastname}">
            </span>
             {if isset($errors["lastname"])}
            <span class="error">
                {echo join("<br/>", $errors["lastname"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Email*</label>
            <span class="field">
                <input type="email" name="email" class="longinput" required value="{echo $user->email}">
            </span>
            {if isset($errors["email"])}
            <span class="error">
                {echo join("<br/>", $errors["email"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Heslo*</label>
            <span class="field">
                <input type="password" name="password" class="longinput" value="">
            </span>
            {if isset($errors["password"])}
            <span class="error">
                {echo join("<br/>", $errors["password"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Heslo znovu*</label>
            <span class="field">
                <input type="password" name="password2" class="longinput" value="">
            </span>
            {if isset($errors["password2"])}
            <span class="error">
                {echo join("<br/>", $errors["password2"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Datum narození*</label>
            <span class="field">
                <input type="text" name="dob" class="longinput datepicker-registration" value="{echo $user->dob}">
            </span>
            {if isset($errors["dob"])}
            <span class="error">
                {echo join("<br/>", $errors["dob"])}
            </span>
            {/if}
        </p>
        <p>
            <label>ČFBU PersonalID*</label>
            <span class="field">
                <input type="text" name="cfbuPersonalNum" class="longinput" required value="{echo $user->cfbuPersonalNum}">
            </span>
            {if isset($errors["cfbuPersonalNum"])}
            <span class="error">
                {echo join("<br/>", $errors["cfbuPersonalNum"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Foto</label>
            <span class="field">
                <img src="{echo $user->photo}" alt="" />
                <input type="file" name="photo" class="longinput">
            </span>
            {if isset($errors["photo"])}
            <span class="error">
                {echo join("<br/>", $errors["photo"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Číslo dresu*</label>
            <span class="field">
                <input type="number" min="0" max="99" name="playerNum" class="longinput" value="{echo $user->playerNum}">
            </span>
            {if isset($errors["playerNum"])}
            <span class="error">
                {echo join("<br/>", $errors["playerNum"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Team*</label>
            <span class="field">
                <select name="team" class="longinput">
                    {if $user->team == "a"}
                    <option value="a" selected=selected>A</option>
                    <option value="b">B</option>
                    {/if}
                    {else}
                    <option value="a">A</option>
                    <option value="b" selected=selected>B</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["team"])}
            <span class="error">
                {echo join("<br/>", $errors["team"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Nick</label>
            <span class="field">
                <input type="text" name="nickname" class="longinput" value="{echo $user->nickname}">
            </span>
            {if isset($errors["nickname"])}
            <span class="error">
                {echo join("<br/>", $errors["nickname"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Pozice*</label>
            <span class="field">
                <select name="position" class="longinput">
                    {if $user->position == "u"}
                    <option value="u" selected=selected>Útočník</option>
                    <option value="o">Obránce</option>
                    <option value="b">Brankář</option>
                    {/if}
                    {elseif $user->position == "o"}
                    <option value="u">Útočník</option>
                    <option value="o" selected=selected>Obránce</option>
                    <option value="b">Brankář</option>
                    {/elseif}
                    {else}
                    <option value="u">Útočník</option>
                    <option value="o">Obránce</option>
                    <option value="b" selected=selected>Brankář</option>
                    {/else}

                </select>
            </span>
            {if isset($errors["position"])}
            <span class="error">
                {echo join("<br/>", $errors["position"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Držení hole*</label>
            <span class="field">
                <select name="grip" class="longinput">
                    {if $user->grip == "r"}
                    <option value="r" selected=selected>Pravá</option>
                    <option value="l">Levá</option>
                    {/if}
                    {else}
                    <option value="r">Pravá</option>
                    <option value="l" selected=selected>Levá</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["grip"])}
            <span class="error">
                {echo join("<br/>", $errors["grip"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Další</label>
            <span class="field">
                <textarea cols="15" rows="5" name="other" class="longinput">{echo $user->other}</textarea>
            </span>
            {if isset($errors["other"])}
            <span class="error">
                {echo join("<br/>", $errors["other"])}
            </span>
            {/if}
        </p>
        <p>
            <span class="field">
                <input type="submit" name="editProfile" value="Uložit změny" />
            </span>
        </p>
    </form>
</article>