<article class="grid_12">
    <h1 class="left">Matches</h1>
    <a class="button-orange right" href="/admin/match/add/">+ Add match</a>
    <div class="clear"></div><br/><br/>

    {if !empty($matchesA)}
    <h2>Team A</h2>
    <table class="dt-base">
        <thead>
        <th>Date</th><th>Home</th><th>Host</th>
        <th>Hall</th><th>Active</th>
        <th>Created</th><th>Manage</th>
        </thead>
        <tbody>
            {foreach $match in $matchesA}
            <tr>
                <td>{echo date("d.m. Y", strtotime($match->date))}</td>
                <td>{echo $match->home}</td>
                <td>{echo $match->host}</td>
                <td>{echo $match->hall}</td>
                <td>{echo $match->active}</td>
                <td>{echo $match->created}</td>
                <td>
                    <a class="button-edit" href="/admin/match/edit/{echo $match->id}" >Edit</a>
                    <a class="button-delete" href="/admin/match/delete/{echo $match->id}" >Delete</a>
                    <a class="button-comment" href="/admin/match/showMessages/" >Messages</a>
                </td>
            </tr>
            {/foreach}
        </tbody>
    </table>
    {/if}
    <br/><br/>
    {if !empty($matchesB)}
    <h2>Team B</h2>
    <table class="dt-base">
        <thead>
        <th>Date</th><th>Home</th><th>Host</th>
        <th>Hall</th><th>Active</th>
        <th>Created</th><th>Manage</th>
        </thead>
        <tbody>
            {foreach $match in $matchesB}
            <tr>
                <td>{echo date("d.m. Y", strtotime($match->date))}</td>
                <td>{echo $match->home}</td>
                <td>{echo $match->host}</td>
                <td>{echo $match->hall}</td>
                <td>{echo $match->active}</td>
                <td>{echo $match->created}</td>
                <td>
                    <a class="button-edit" href="/admin/match/edit/{echo $match->id}" >Edit</a>
                    <a class="button-delete" href="/admin/match/delete/{echo $match->id}" >Delete</a>
                    <a class="button-comment" href="/admin/match/showMessages/" >Messages</a>
                </td>
            </tr>
            {/foreach}
        </tbody>
    </table>
    {/if}
</article>