<article>
    <h1>K Zápasu</h1>

    {if isset($matchMessages)}
    {foreach $message in matchMessages}
    <article class="messageWrapper relative">
        <div class="message">
            <span class="title">{echo $message->title}</span><br/>
            <p class="messageBody">{echo $message->body}</p>
            <span class="meta">Autor: {echo $message->author} </span>
            <span class="meta">Vytvořeno: {echo date("d.m. Y H:i", strtotime($message->created))} </span>
            <a href="/admin/match/deleteMessage/{echo $message->id}">Delete</a><br/>
        </div>
        <div class="clear"></div>

        {script $replies = App_MatchChatModel::fetchReplies($message->id)}
        {foreach $reply in $replies}
        <div class="reply">
            <span class="title">{echo $reply->title}</span><br />
            <p class="messageBody">{echo $reply->body}</p>
            <span class="meta">Autor: {echo $reply->author} </span>
            <span class="meta">Vytvořeno: {echo date("d.m. Y H:i", strtotime($reply->created))}</span>
            <a href="/admin/match/deleteMessage/{echo $reply->id}">Delete</a>
        </div>
        <div class="clear"></div>
        {/foreach}
    </article>
    {/foreach}
    {/if}
   
</article>