<div class="queueDiv">
    {foreach $bla in $qarray}
    <div class="qUserWrapper">
        <div class="qUserName">
            {echo $bla->firstname." ".$bla->lastname}
        </div>
        <form method="post" action="/admin/index/changeStatus/{echo $bla->id}" class="qButtons">
            <input type="submit" class="qChangeStatus" value="Active"/>
        </form>
    </div>
    {/foreach}
</div>
<header class="chatHeader">
    <div class="logout">
        <a href="/admin/logout">X</a>
    </div>
    <div class="info">
        Online Chat
    </div>
</header>
<div class="chatWindow">
    <div class="chatContentWrapper">
        <div class="chatContent">
            <div class="messageWrapper">
                               
                {foreach $k in $vypiskonverzace}

                {if $k->from = 1}
                <div  class="messageNameRed">
                    {echo $k->firstname." ".$k->lastname}          
                </div>
                {/if}
                {if $k->from <> 1} 
                <div  class="messageNameBlue">
                    {echo $k->firstname." ".$k->lastname}
                </div>
                {/if}

                <div class="message">
                    {echo $k->message}
                </div>
                {/foreach}        
               
            </div>


        </div>

        <div class="chatInputs">
            <form id="inputForm" method="post" action="/admin/submitChat">

                {if isset($error)}
                <span class="error">
                    {echo $error}
                </span>
                {/if}

                <br/>
                <input type="text" name="chatTextInput" class="chatTextInput" required/>
                <input type="submit" name="chatTextSubmit" value="Odeslat" />
            </form>
        </div>

    </div>
</div>