<article class="grid_12">
    <h1>Dashboard</h1>
    <br/>
    <div class="grid_3">
        <a class="dashboard-button" href="/admin/news/add/">Add news</a>
    </div>
    
    <div class="grid_3">
        <a class="dashboard-button" href="/admin/match/add/">Add match</a>
    </div>
    
    <div class="grid_3">
        <a class="dashboard-button" href="/admin/training/add/">Add training</a>
    </div>
    
    <div class="grid_3">
        <a class="dashboard-button" href="/admin/user/add/">Add user</a>
    </div>
</article>

<article class="grid_12">
    <div class="grid_3">
        <a class="dashboard-button" href="/admin/gallery/add/">Add gallery</a>
    </div>
</article>