<article class="grid_12">
    <h1>Add training</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" required value=""/>
            </span>
            {if isset($errors["title"])}
            <span class="error">
                {echo join("<br/>", $errors["title"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Date*</label>
            <span class="field">
                <input type="text" name="date" class="longinput datepicker" required value="">
            </span>
            {if isset($errors["date"])}
            <span class="error">
                {echo join("<br/>", $errors["date"])}
            </span>
            {/if}
        </p>
        <p>
            <span class="field">
                <input type="submit" name="addTraining" value="Add training" />
            </span>
        </p>
    </form>
</article>