<article class="grid_12">
    <h1>Training attendace</h1>

    {if !empty($attd)}
    <h2>Total trainings count: {echo $trcount}</h2>
    <table class="dt-base">
        <thead>
        <th>Firstname</th><th>Lastname</th>
        <th>Visited</th><th>Proc</th>
        </thead>
        <tbody>
            {foreach $attend in $attd}
            <tr>
                <td>{echo $attend["firstname"]}</td>
                <td>{echo $attend["lastname"]}</td>
                <td>{echo $attend["cnt"]}</td>
                <td>{echo $attend["proc"]}</td>
            </tr>
            {/foreach}
        </tbody>
    </table>
    {/if}
</article>