<article class="grid_12">
    <h1>Delete training</h1>

    <form method="post" action="#" class="stdform">
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" class="mediuminput" disabled value="{echo $training->title}"/>
            </span>
        </p>
        <p>
            <label>Date</label>
            <span class="field">
                <input type="text" name="date" class="mediuminput" disabled value="{echo $training->date}"/>
            </span>
        </p>
        <p>
            <span class="field">
                <input type="submit" name="deleteTraining" value="Delete training" />
                <input type="submit" name="cancel" value="Cancel" />
            </span>
        </p>
    </form>
</article>