<article class="grid_12">
    <h1>Edit training</h1>
    <form method="post" action="#" class="stdform">
        <p>
            <label>Title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" required value="{echo $training->title}"/>
            </span>
            {if isset($errors["title"])}
            <span class="error">
                {echo join("<br/>", $errors["title"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Date*</label>
            <span class="field">
                <input type="text" name="date" class="longinput datepicker" required value="{echo $training->date}" />
            </span>
            {if isset($errors["date"])}
            <span class="error">
                {echo join("<br/>", $errors["date"])}
            </span>
            {/if}
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $training->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["active"])}
            <span class="error">
                {echo join("<br/>", $errors["active"])}
            </span>
            {/if}
        </p>
        <p>
            <span class="field">
                <input type="submit" name="editTraining" value="Save changes" />
            </span>
        </p>
    </form>
</article>