<article class="grid_12">
    <h1 class="left">Training list</h1>
    <a class="button-orange right" href="/admin/training/add/">+ Add training</a>
    <a class="button-orange right" href="/admin/training/attendance/">Check attendance</a>
    <div class="clear"></div><br/><br/>

    {if !empty($trainings)}
    <table class="dt-base">
        <thead>
        <th>Title</th><th>Date</th>
        <th>Active</th><th>Created</th><th>Manage</th>
        </thead>
        <tbody>
            {foreach $training in $trainings}
            <tr>
                <td>{echo $training->title}</td>
                <td>{echo $training->date}</td>
                <td>{echo $training->active}</td>
                <td>{echo $training->created}</td>
                <td>
                    <a class="button-edit" href="/admin/training/edit/{echo $training->id}" >Edit</a>
                    <a class="button-delete" href="/admin/training/delete/{echo $training->id}" >Delete</a>
                    <a class="button-person" href="/admin/training/showAttendance/{echo $training->id}" >Attendance</a>
                </td>
            </tr>
            {/foreach}
        </tbody>
    </table>

    {/if}
</article>