<article class="grid_12">
    <h1>Training attendace</h1>

    {if !empty($training)}
    <div class="grid_12 trainingWrapper">
        <div class="trainingCalIcon">
            <img src="/public/images/icons/calendar.png" alt="" />
        </div>
        <div>
            <h2>{echo $training->title} - {echo date("d.m. Y", strtotime($training->date))}</h2>
            <br/>
            {script $ucast = $neucast = $nevi=array();$countU = $countN = $countM=0}

            {foreach $attd in $training->attendance}
            {if $attd["status"]==1}
                {script $ucast[] = $attd["firstname"]." ".$attd["lastname"]; $countU++}
            {/if}
            {elseif $attd["status"] == 2}
                {script $neucast[] = $attd["firstname"]." ".$attd["lastname"]; $countN++}
            {/elseif}
            {elseif $attd["status"] == 3}
                {script $nevi[] = $attd["firstname"]." ".$attd["lastname"]; $countM++}
            {/elseif}
            {/foreach}

            <div class="trainingResult">
                <div>
                    Přijde ({echo $countU}):  {echo implode(", ", $ucast)}
                </div>
                <div>
                    Nepřijde ({echo $countN}):  {echo implode(", ", $neucast)}
                </div>
                <div>
                    Možná ({echo $countM}):  {echo implode(", ", $nevi)}
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    {/if}
</article>
