<p>
    <span class="datumakt"></span>
    <br/>
    <img width="570" border="0" height="21" src="/public/images/obsahtecky12.gif">
    <br/>
    <span class="nadpiszeleny">Den otevřených dveří 2013</span>
    <br/>
    <img width="570" vspace="5" border="0" height="1" src="/public/images/rozdel.gif">
    <br/>
    <img width="57" border="0" height="21" src="/public/images/obsahtecky13.gif">
    <br/>

    <br/>
<table class="contentTable">
    <tbody>
        <tr>
            <td colspan="2">
                <h1>Pátek 23. května 2014</h1>
                <br>
                <br>
            </td>
        </tr>
        <tr>
            <td>
                <h2> 12.00 </h2>
            </td>
            <td>Zahájení, uvítání zájemců o studium ředitelem školy </td>
        </tr>
        <tr>
            <td>
                <h2>12.15</h2>
            </td>
            <td>Prezentace studijních programů </td>
        </tr>
        <tr>
            <td>
                <h2>12.45</h2>
            </td>
            <td>Diskuse se zástupci studijních programů </td>
        </tr>
        <tr>
            <td>
                <h2>13.00</h2>
            </td>
            <td>
                Prohlídka školy
                <br>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <br>
                <i>Den otevřených dveří je určen přednostně pro zájemce o vyšší odborné studium, ale přivítáme samozřejmě i zájemce o ostatní formy studia.</i>
            </td>
        </tr>
    </tbody>
</table>
<br/>
<br/>
<span class="podtitul">
    <img width="570" vspace="5" border="0" height="1" src="/public/images/rozdel.gif"/>
    <br/>
    Prosíme o vyplnění registrace - všichni registrovaní obdrží na dni otevřených dveří drobný dárek.
</span>
</p>

<form class="stdform" method="post" action="">
    <table cellspacing="5">
        <tbody>
            <tr>
                <td>
                    Jméno:
                    <br>
                    <input class="mediuminput" type="text" value="" size="30" name="FIRSTNAME">
                </td>&nbsp;
                <td>
                    Příjmení:
                    <br>
                    <input class="mediuminput" type="text" value="" size="30" name="SURNAME">
                </td>
            </tr>
        </tbody>
    </table>
    <table>
        <tbody>
            <tr>
                <td>
                    E-mail:
                    <br>
                    <input class="longinput" type="text" value="" size="50" name="EMAIL">
                </td>
            </tr>
        </tbody>
    </table>
    <input id="Odeslano" type="hidden" value="1" name="Odeslano">
    <input type="submit" value="Potvrdit registraci" name="doreg">
</form>