<table width="100%" cellpadding="0" border="0" height="28" cellspacing="0">
    <tbody>
        <tr height="28">
            <td background="public/images/hornipruhnek.gif">
                <img width="137" border="0" height="28" src="public/images/hornipruh1.gif">
            </td>
        </tr>
    </tbody>
</table>
<table width="100%" cellpadding="0" border="0" height="75" cellspacing="0">
    <tbody>
        <tr>
            <td width="137" background="public/images/vosishorni.gif" height="105" rowspan="2">
                <a target="_top" href="http://www.sks.cz">
                    <img width="137" border="0" height="75" src="public/images/logoVOSIS_01.gif">
                </a>
                <br>
                <img width="137" border="0" height="30" src="public/images/logoVOSIS_02.gif">
            </td>
            <td background="public/images/vosishorni.gif" height="75">
                <img width="9" border="0" height="75" src="public/images/vosishorniobr.gif">
                <embed width="550" height="75" src="public/images/banner.swf" bgcolor="#174D41" wmode="transparent" play="true" quality="best" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash">
            </td>
        </tr>
        <tr>
            <td class="bla"  background="public/images/menupruh.gif" align="right" height="30">
                <span class="odkaz">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="obsah" href="obsah.phtml">VOŠIS</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="_top" href="http://erasmus.sks.cz/incomings">English</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="obsah" href="hledej/index.phtml">Vyhledávání</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="obsah" href="oskole/kontakt.html">Kontakt</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="obsah" href="oskole/FAQ.phtml">FAQ</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="_top" href="http://mail.sks.cz">Mail</a>
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <img width="6" border="0" src="public/images/menutecka2.gif">
                    <img width="5" border="0" height="5" src="public/images/spacer.gif">
                    <a target="_top" href="https://dvere.sks.cz/intra/index.phtml">Intranet</a>
                    <img width="25" border="0" height="5" src="public/images/spacer.gif">
                </span>
            </td>
        </tr>
    </tbody>
</table>
