<!doctype html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <title>Error 503</title>
        <!---CSS Files-->
        <link rel="stylesheet" href="/public/css/errorStyle.css">
    </head>
    <body>
        <div class="content container_12">
            <h1 id="error-heading">503</h1>
            <p id="error-desc">Service temporarily unavailable.<br><br>
                Please wait while the firemen put out our melting servers.</p>
            <p id="error-back">Please try again in a few minutes. <a href="#">Refresh</a>
            </p>
        </div>
        <div class='content container_12'>
            <?php if (DEBUG): ?>
                <pre><?php print_r($e); ?></pre>
            <?php endif; ?>
        </div>
        <div class="footer container_12">
            <p class="grid_12">THCFrame Error Page</p>
        </div>
    </body>
</html>