<nav>
    <ul id="menu">
        {if !isset($authUser)}
        <li id="active"><a href="/">Pedak</a></li>
        <li class="end"><a href="/admin/login">Login</a></li>
        {/if}
        {else}
        <li id="active"><a href="/admin/">Home</a></li>
        <li><a href="/admin/news/">News</a></li>
        <li><a href="/admin/match/">Matches</a></li>
        <li><a href="/admin/gallery/">Gallery</a></li>
        <li><a href="/admin/training/">Trainings</a></li>
        <li><a href="/admin/sponsor/">Sponsors</a></li>
        <li><a href="/admin/user/">Users</a></li>
        <li class="end"><a href="/admin/logout">Logout</a></li>
        {/else}
    </ul>
</nav>