<header class="chatHeader">
    <div class="logout">
        <a href="/logout"><img class="logoutImage" src="/public/images/x.png"></a>

    </div>
    <div class="info">
        Online Chat
    </div>
</header> 

<article id="loginStep">
    <div class="errorBox"></div>
    <div class="info">
        Vítejte na online chatu.<br/>
        Vyplňte následující údaje
    </div>
    <div class="chatContent">
        <form action="#" method="post">

            <table class="login">
                <tr><td><label for="name">Jméno</label> <br/><input class="chatTextInput" type="text" name="firstname" required maxlength="30"/><br/></td></tr>
                <tr><td><label for="email">Příjmení</label><br/><input class="chatTextInput" type="text" name="lastname" required maxlength="30" /></td></tr>
            </table>
            <div class="buttonWrapper">
                <input class="chatButton" id="loginButton" type="button" name="continue" value="Pokračovat"/>    
            </div>
        </form>
    </div>
</article>

<article id="chatStep">
    <div class="chatContentWrapper">
        <div class="chatContent">
            <div class="loader"><img src="/public/images/loader1.gif" alt="Loading Icon" /></div>
            <div id="messageWrapper2"></div>
        </div>

        
        <div class="chatInputs no-display">
            <form id="inputForm" method="post" action="/submitChat">

                {if isset($error)}
                <span class="error">
                    {echo $error}
                </span>
                {/if}
                <span id="writingIndicator" class="no-display">Operátor píše....</span>
                <br/>
                <textarea class="chatTextarea" id="chatTextarea" rows="3" cols="25" name="chatTextInput" required></textarea>
                <div class="chatButtonWrapper">
                    <input class="chatButton" type="submit" name="chatTextSubmit" value="Odeslat" />
                </div>
            </form>
        </div>
        <audio id="activeSound">
            <source src="/public/sound/pizzicato.ogg"></source>
            <source src="/public/sound/pizzicato.mp3"></source>
        </audio>
      

    </div>
</article>


